name: Create, Publish, and Deploy Docker image

on:
  release:
    types:
      - published

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push-server-image:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: ${{ github.repository }}/server

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, lavels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  render-deployment:
    runs-on: ubuntu-latest

    needs:
      - build-and-push-server-image

    steps:
      - name: Deploy to render after ghcr image uploads
        run: |
          curl ${{ secrets.RENDER_SERVER_HOOK }}
